
export global MainWindowStyle {
    out property <brush> background: #ffffff;

    out property <length> width: 1024px;
    out property <length> height: 768px;
}

export global NavbarStyle {
    out property <brush> background: #adadad;

    out property <length> width: 1024px;
    out property <length> height: 100px;

    out property <length> font-size: 16px;
}

export global ButtonStyles {
    out property <brush> default-background: #4b73f7;
    out property <brush> success-background: #4CAF50;
    out property <brush> danger-background: #f44336;

    out property <brush> default-foreground: #000000;
    out property <brush> success-foreground: #ffffff;
    out property <brush> danger-foreground: #ffffff;

    out property <int> button-text-weight: 500;
    out property <length> button-text-size: 16px;

    out property <length> button-width: 120px;
    out property <length> button-height: 40px;

    out property <length> button-border-radius: 10px;
}

export global OneLineInputStyles {
    out property <brush> font-color: #000000;
    out property <brush> garied-font-color: #7a7a7a;
    out property <length> font-size: 16px;
    
    out property <length> width: 200px;
    out property <length> height: 30px;
    
    out property <brush> background: #ffffff;
    out property <brush> border-color: #cccccc;
    out property <length> border-width: 1px;
    out property <length> border-radius: 10px;
}

export global DropdownStyles {
    out property <brush> font-color: #000000;
    out property <brush> garied-background-color: #f5f5f5;
    out property <length> font-size: 16px;
    out property <int> font-weight: 400;
    out property <brush> border-color: #cccccc;
}

export global FilterStyles {    
    out property <brush> background: #ffffff;
    out property <brush> border-color: #000000;
    out property <length> border-width: 1px;
    out property <length> border-radius: 10px;
    out property <length> width: 300px;
    out property <length> height: 40px;

}


export global ProductContainerStyles {
    out property <brush> background: #ffffff;
    out property <brush> font-color: #525252;
    out property <length> font-size: 16px;
    out property <int> font-weight: 400;

    out property <length> width: 200px;
    out property <length> height: 230px;

    out property <length> image-width: 150px;
    out property <length> image-height: 100px;
    out property <brush> border-color: #cccccc;

    out property <length> title-font-size: 20px;
    out property <int> title-font-weight: 500;
    out property <brush> title-color: #000000;

    out property <length> category-font-size: 14px;
    out property <int> category-font-weight: 400;
    out property <brush> category-font-color: #ffffff;
    out property <brush> category-background: #3200e7;
    out property <length> category-border-radius: 5px;
    out property <length> category-width: 120px;
    out property <length> category-height: 25px;
}
