import { DropdownStyles } from "../style/defaults.slint";

export component CustomDropdown inherits Rectangle {
    in property <[string]> model: [];
    in-out property <string> current-value: model[0];
    in property <brush> font-color: DropdownStyles.font-color;
    in property <length> font-size: DropdownStyles.font-size;
    in property <int> font-weight: DropdownStyles.font-weight;
    in property <brush> dropdown-background: DropdownStyles.garied-background-color;
    in property <image> icon;

     property <length> icon-offset: icon.width > 0 ? root.height + 4px : 0px;
    
    callback selected(string);

    property <brush> bg: dropdown-background;
    property <bool> open: false;

    background: main-touch.pressed ? bg.darker(30%) : main-touch.has-hover ? bg.brighter(20%) : bg;
    border-radius: 6px;
    height: font-size + 8px;
    clip: false;

     if icon.width > 0: Image {
        x: 4px;
        y: (parent.height - self.height) / 2;
        width: parent.height;
        height: parent.height;
        source: icon;
    }

    Text {
        x: 8px + icon-offset;
        width: parent.width - 16px;
        height: parent.height;
        text: current-value;
        color: root.font-color;
        font-size: root.font-size;
        font-weight: root.font-weight;
        vertical-alignment: center;
    }

    main-touch := TouchArea {
        clicked => {
            open = !open;
            if open { dropdown-popup.show(); }
        }
    }

    dropdown-popup := PopupWindow {
        x: 0px;
        y: root.height + 2px;
        width: root.width;
        height: model.length * (root.font-size + 8px);
        close-policy: close-on-click-outside;

        Rectangle {
            width: parent.width;
            height: parent.height;
            background: root.bg;
            border-radius: 6px;
            border-width: 1px;
            border-color: DropdownStyles.border-color;

            VerticalLayout {
                for item in model: Rectangle {
                    background: item-touch.pressed ? root.bg.darker(30%) : item-touch.has-hover ? root.bg.brighter(20%) : root.bg;
                    height: root.font-size + 8px;

                    item-touch := TouchArea {
                        clicked => {
                            current-value = item;
                            selected(item);
                            open = false;
                            dropdown-popup.close();
                        }
                    }

                    Text {
                        x: 8px;
                        height: parent.height;
                        text: item;
                        color: root.font-color;
                        font-size: root.font-size;
                        vertical-alignment: center;
                    }
                }
            }
        }
    }
}