import { FilterStyles, DropdownStyles } from "../style/defaults.slint";
import { CustomDropdown } from "./dropdown.slint";
import { Icons } from "../style/icons.slint";

export component Filter inherits Rectangle {
    in property <[string]> categories: ["Tot"];
    callback category-selected(string);

    width: FilterStyles.width;
    height: FilterStyles.height;
    background: FilterStyles.background;
    border-color: FilterStyles.border-color;
    border-width: FilterStyles.border-width;
    border-radius: FilterStyles.border-radius;

    property <length> spacing: 10px;

    HorizontalLayout {
        spacing: root.spacing;
        padding-left: 10px;
        padding-top: root.height / 2 - bydropdown.height / 2;
        alignment: start;

        Text {
            text: "Categorie: ";
            color: DropdownStyles.font-color;
            font-size: DropdownStyles.font-size;
            font-weight: DropdownStyles.font-weight;
        }

        bydropdown := CustomDropdown {
            width: 140px;
            model: categories;
            current-value: categories[0];
            background: root.background;
            dropdown-background: root.background;
            icon: Icons.filter;
            selected(val) => { root.category-selected(val); }
        }
    }
}
