import { FilterStyles, DropdownStyles } from "../style/defaults.slint";
import { CustomDropdown } from "./dropdown.slint";
import { Icons } from "../style/icons.slint";

export component Filter inherits Rectangle {
    
    width: FilterStyles.width;
    height: FilterStyles.height;
    background: FilterStyles.background;
    border-color: FilterStyles.border-color;
    border-width: FilterStyles.border-width;
    border-radius: FilterStyles.border-radius;

    property <length> spacing: 10px;

    HorizontalLayout {
        spacing: root.spacing;
        padding-left: 10px;
        padding-top: root.height / 2 - bydropdown.height / 2 ;
        alignment: start;

        Text {
            text: "Categorie: ";
            color: DropdownStyles.font-color;
            font-size: DropdownStyles.font-size;
            font-weight: DropdownStyles.font-weight;
        }

        bydropdown := CustomDropdown {
            width: 100px;
            model: ["Tot", "Electrozi", "Sarma", "Abrazive", "Pistoleti", "Accesorii", "Reductoare", "Protectie", "Chimicale"];
            current-value: "Tot";
            background: root.background;
            dropdown-background: root.background;
            icon: Icons.filter;
        }

    }
}
