import { OneLineInputStyles, ButtonStyles } from "../style/defaults.slint";

export component OneLineInput inherits Rectangle {
    in-out property <string> txt;
    in property <string> placeholder-text: "Cauta...";
    in property <image> icon;
    in property <InputType> input-type: text;

    width: OneLineInputStyles.width;
    height: ButtonStyles.button-height;

    property <length> icon-offset: icon.width > 0 ? root.height + 4px : 0px;

    background: OneLineInputStyles.background;
    border-color: OneLineInputStyles.border-color;
    border-width: OneLineInputStyles.border-width;
    border-radius: OneLineInputStyles.border-radius;

    if icon.width > 0: Image {
        x: 4px;
        y: (parent.height - self.height) / 2;
        width: parent.height;
        height: parent.height;
        source: icon;
    }

    if txt == "": Text {
        x: 10px + icon-offset;
        y: (parent.height - self.height) / 2;
        text: placeholder-text;
        color: OneLineInputStyles.garied-font-color;
        font-size: OneLineInputStyles.font-size;
    }

    TextInput {
        x: 10px + icon-offset;
        width: parent.width - 20px - icon-offset;
        height: parent.height;
        vertical-alignment: center;
        text <=> root.txt;
        color: OneLineInputStyles.font-color;
        font-size: OneLineInputStyles.font-size;
        cursor-position-changed(position) => {
        }
        input-type: root.input-type;
    }
}
