import { OneLineInput } from "../components/onelineinput.slint";
import { LoginStyle } from "../style/defaults.slint";
import { CustomButton } from "../components/button.slint";


export component LoginView inherits Rectangle {

    callback login(string, string, string);  // (server_url, username, password)
    in-out property <string> server-url;

    background: LoginStyle.background;

    VerticalLayout {
        spacing: 10px;
        alignment: center;

        HorizontalLayout {
            alignment: center;
            Text {
                text: "Server URL: ";
                font-size: LoginStyle.font-size;
                color: LoginStyle.font-color;
                font-weight: LoginStyle.font-weight;
            }

            server-input := OneLineInput {
                placeholder-text: "https://example.com";
                width: 300px;
                txt: root.server-url;
                accepted => {
                    root.login(self.txt, username-input.txt, password-input.txt);
                }
            }
        }

        HorizontalLayout {
            alignment: center;
            Text {
                text: "Username: ";
                font-size: LoginStyle.font-size;
                color: LoginStyle.font-color;
                font-weight: LoginStyle.font-weight;
            }

            username-input := OneLineInput {
                placeholder-text: "username";
                width: 300px;
                accepted => {
                    root.login(server-input.txt, self.txt, password-input.txt);
                }
            }
        }

        HorizontalLayout {
            alignment: center;
            Text {
                text: "Password: ";
                font-size: LoginStyle.font-size;
                color: LoginStyle.font-color;
                font-weight: LoginStyle.font-weight;
            }

            password-input := OneLineInput {
                placeholder-text: "password";
                input-type: password;
                width: 300px;
                accepted => {
                    root.login(server-input.txt, username-input.txt, self.txt);
                }
            }
        }

        HorizontalLayout {
            alignment: center;
            CustomButton {
                text: "Log in";
                clicked => {
                    root.login(server-input.txt, username-input.txt, password-input.txt);
                }
            }
        }
    }
}
