import { Button, VerticalBox } from "std-widgets.slint";
import { MainWindowStyle } from "style/defaults.slint";
import { NavBar } from "components/nav.slint";
import { Filter } from "components/filter.slint";

export component Main inherits Window {
    width: MainWindowStyle.width;
    height: MainWindowStyle.height;
    background: MainWindowStyle.background;

    VerticalLayout {
        spacing: 5px;
        alignment: start;
        NavBar {
        }
        Filter {
            x: 10px;
        }

    }
}